#!/bin/bash
URL_LIST="http://incompetech.com/music/royalty-free/mp3-royaltyfree/Batty%20McFaddin.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Iron%20Horse.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Merry%20Go.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Batty%20McFaddin%20-%20Slower.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Merry%20Go%20Slower.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Merry%20Go%20-%20Distressed.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Villainous%20Treachery%20-%20Distressed.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Merry%20Go%20Slower%20-%20Distressed.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Amazing%20Plan%20-%20Distressed.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Amazing%20Plan.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Villainous%20Treachery.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Iron%20Horse%20-%20Distressed.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Grammophone%20Taps.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Fig%20Leaf%20Rag.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Fig%20Leaf%20Rag%20-%20distressed.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Dark%20Hallway%20-%20Distressed.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Bad%20Ideas%20_distressed_.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Dark%20Hallway.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Bad%20Ideas%20_clean_.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Comic%20Plodding.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Water%20Droplets%20on%20the%20River.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Keystone%20Deluge.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Plucky%20Daisy.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Look%20Busy.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Gold%20Rush.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Breaktime.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Olde%20Timey.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Heroic%20Reception.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Five%20Card%20Shuffle.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Barroom%20Ballet.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Mr%20Mealeys%20Mediocre%20Machine.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Hand%20Trolley.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Doh%20De%20Oh.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Hammock%20Fight.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Aunt%20Tagonist.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Mister%20Exposition.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/The%20Chase%20FX.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Piano%20Cue%20One.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Evil%20Plan%20FX.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Friendly%20Day.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Comic%20Hero.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Royal%20Banana.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Circus%20Waltz%20FX.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Waltz%20of%20Treachery%20FX.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Super%20Circus.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Work%20is%20Work%20FX.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/The%20Bandit.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Trouble.mp3"
URL_LIST="$URL_LIST http://incompetech.com/music/royalty-free/mp3-royaltyfree/Fig%20Leaf%20Times%20Two.mp3"

for url in $URL_LIST
do
    wget $url
done